[package]
name = "ecma_compat"
version = "0.1.0"
edition = "2024"

[dependencies]
oxc = { workspace = true, features = ["ast_visit"] }
browserslist-rs={workspace = true}
serde_json = { workspace = true }
serde = { workspace = true }
sourcemap = { workspace = true }
thiserror={workspace = true}
path-slash = {workspace = true}
