[package]
name = "ecma_compat_binding"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
test = false

[dependencies]
ecma_compat = { workspace = true }
napi = { workspace = true }
napi-derive = { workspace = true }
rayon = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
