/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeCwd(cwd: string, targets: Array<string>, options?: AnalyzeCwdOptions | undefined | null): JsCompatDirectoryReport

export interface AnalyzeCwdOptions {
  includeSupportedTargets?: boolean
  extensions?: Array<string>
  sourceMaps?: boolean
  parallelism?: number
  maxFileSizeBytes?: number
}

export declare function analyzePath(path: string, targets: Array<string>, options?: AnalyzePathOptions | undefined | null): JsCompatFileReport

export interface AnalyzePathOptions {
  includeSupportedTargets?: boolean
  sourceMaps?: boolean
}

export interface JsCompatDiagnostic {
  feature: string
  path: string
  span: JsSourceSpan
  generatedPosition: JsSourcePosition
  sourceMapping: JsSourceMapping
  targetStatuses: Array<JsTargetCompatStatus>
}

export interface JsCompatDirectoryReport {
  cwd: string
  fileCount: number
  skippedFileCount: number
  diagnosticCount: number
  reports: Array<JsCompatFileReport>
  errors: Array<JsCompatFileError>
  skipped: Array<JsSkippedFile>
}

export interface JsCompatFileError {
  path: string
  message: string
}

export interface JsCompatFileReport {
  path: string
  targets: Array<JsRuntimeTarget>
  detectedUsageCount: number
  sourceMapStatus: JsSourceMapStatus
  diagnostics: Array<JsCompatDiagnostic>
}

export interface JsRuntimeTarget {
  runtime: string
  release: string
}

export interface JsSkippedFile {
  path: string
  size: number
}

export interface JsSourceMapping {
  kind: string
  source?: string
  start?: JsSourcePosition
  end?: JsSourcePosition
  reason?: string
}

export interface JsSourceMapStatus {
  kind: string
  discoveryKind?: string
  reference?: string
  sourceCount?: number
  reason?: string
}

export interface JsSourcePosition {
  line: number
  column: number
}

export interface JsSourceSpan {
  start: number
  end: number
}

export interface JsTargetCompatStatus {
  target: JsRuntimeTarget
  status: string
}
