/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeCwd(cwd: string, targets: Array<string>, options?: AnalyzeCwdOptions | undefined | null): JsCompatDirectoryReport

export interface AnalyzeCwdOptions {
  includeSupportedTargets?: boolean
  extensions?: Array<string>
  parallelism?: number
  excludeEmptyReports?: boolean
}

export declare function analyzePath(path: string, targets: Array<string>, options?: AnalyzePathOptions | undefined | null): JsCompatFileReport

export interface AnalyzePathOptions {
  includeSupportedTargets?: boolean
}

export interface JsCompatDiagnostic {
  feature: string
  span: JsSourceSpan
  position: JsSourcePosition
  sourceMapping: JsSourceMapping
  targetStatuses: Array<JsTargetCompatStatus>
}

export interface JsCompatDirectoryReport {
  cwd: string
  targets: Array<JsRuntimeTarget>
  fileCount: number
  diagnosticCount: number
  reports: Array<JsCompatFileReport>
  errors: Array<JsCompatFileError>
  timing: JsDirectoryTiming
}

export interface JsCompatFileError {
  path: string
  message: string
}

export interface JsCompatFileReport {
  path: string
  sourceMapStatus: JsSourceMapStatus
  diagnostics: Array<JsCompatDiagnostic>
}

export interface JsDirectoryTiming {
  elapsedMs: number
  readMs: number
  parseDetectMs: number
  generatedPositionMs: number
  sourceMapMs: number
  originalRangeRecoveryMs: number
  targetEvaluateMs: number
  dtoConversionMs: number
}

export interface JsRuntimeTarget {
  runtime: string
  release: string
}

export interface JsSourceMapping {
  kind: string
  source?: string
  start?: JsSourcePosition
  end?: JsSourcePosition
  reason?: string
}

export interface JsSourceMapStatus {
  kind: string
  discoveryKind?: string
  reference?: string
  reason?: string
}

export interface JsSourcePosition {
  line: number
  column: number
}

export interface JsSourceSpan {
  start: number
  end: number
}

export interface JsTargetCompatStatus {
  targetIndex: number
  status: string
}
