/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function checkDirectory(cwd: string, targets: Array<string>, options?: CheckDirectoryOptions | undefined | null): CompatDirectoryReport

export interface CheckDirectoryOptions {
  includeSupportedTargets?: boolean
  extensions?: Array<string>
  includeGlobs?: Array<string>
  excludeGlobs?: Array<string>
  respectGitignore?: boolean
  ignoreHidden?: boolean
  parallelism?: number
  excludeEmptyReports?: boolean
}

export declare function checkFile(path: string, targets: Array<string>, options?: CheckFileOptions | undefined | null): CompatFileReport

export interface CheckFileOptions {
  includeSupportedTargets?: boolean
}

export interface CompatDiagnostic {
  feature: string
  span: SourceSpan
  position: SourcePosition
  sourceMapping: SourceMapping
  targetStatuses: Array<TargetCompatStatus>
}

export interface CompatDirectoryReport {
  cwd: string
  targets: Array<RuntimeTarget>
  fileCount: number
  diagnosticCount: number
  reports: Array<CompatFileReport>
  errors: Array<CompatFileError>
  timing: DirectoryTiming
}

export interface CompatFileError {
  path: string
  message: string
}

export interface CompatFileReport {
  path: string
  sourceMapStatus: SourceMapStatus
  diagnostics: Array<CompatDiagnostic>
}

export interface DirectoryTiming {
  elapsedMs: number
  readMs: number
  parseDetectMs: number
  generatedPositionMs: number
  sourceMapMs: number
  originalRangeRecoveryMs: number
  targetEvaluateMs: number
  dtoConversionMs: number
}

export interface RuntimeTarget {
  runtime: string
  release: string
}

export interface SourceMapping {
  kind: string
  source?: string
  start?: SourcePosition
  end?: SourcePosition
  reason?: string
}

export interface SourceMapStatus {
  kind: string
  discoveryKind?: string
  reference?: string
  reason?: string
}

export interface SourcePosition {
  line: number
  column: number
}

export interface SourceSpan {
  start: number
  end: number
}

export interface TargetCompatStatus {
  targetIndex: number
  status: string
}
