#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");

const PACKAGE = "@mdn/browser-compat-data";
const DATA_URL = `https://unpkg.com/${PACKAGE}/data.json`;
const PACKAGE_JSON_URL = `https://unpkg.com/${PACKAGE}/package.json`;
const TARGET = path.join(
  process.cwd(),
  "crates/ecmascript_compatibility/src/database/mdn_generated.rs",
);

const RUNTIME_MAPPINGS = [
  ["InternetExplorer", "ie"],
  ["Edge", "edge"],
  ["Firefox", "firefox"],
  ["Chrome", "chrome"],
  ["Safari", "safari"],
  ["Opera", "opera"],
  ["Ios", "safari_ios"],
  ["OperaMobile", "opera_android"],
  ["ChromeAndroid", "chrome_android"],
  ["FirefoxAndroid", "firefox_android"],
  ["SamsungInternet", "samsunginternet_android"],
  ["Node", "nodejs"],
];

main().catch((error) => {
  console.error(error);
  process.exit(1);
});

async function main() {
  const [packageJson, response] = await Promise.all([
    fetchJson(PACKAGE_JSON_URL),
    fetch(DATA_URL),
  ]);
  if (!response.ok) {
    throw new Error(`failed to fetch ${DATA_URL}: ${response.status}`);
  }

  const packageVersion = packageJson.version;
  const data = await response.json();
  const entries = [];
  collectCompatEntries(data.javascript, ["javascript"], entries);
  entries.sort((left, right) => left.key.localeCompare(right.key));

  fs.writeFileSync(TARGET, renderRust(packageVersion, entries));
  console.log(
    `generated ${entries.length} JavaScript compat entries from ${PACKAGE}@${packageVersion}`,
  );
  console.log(TARGET);
}

async function fetchJson(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`failed to fetch ${url}: ${response.status}`);
  }

  return response.json();
}

function collectCompatEntries(node, pathParts, entries) {
  if (!node || typeof node !== "object") {
    return;
  }

  if (node.__compat?.support) {
    entries.push({
      key: pathParts.join("."),
      support: node.__compat.support,
    });
  }

  for (const [key, value] of Object.entries(node)) {
    if (key !== "__compat") {
      collectCompatEntries(value, [...pathParts, key], entries);
    }
  }
}

function renderRust(packageVersion, entries) {
  const lines = [
    "// @generated by scripts/sync_mdn_bcd.js",
    "// Do not edit by hand. Re-run the script after manually reviewing MDN BCD changes.",
    "",
    "use crate::{",
    "  database::SupportRule,",
    "  target::{Runtime, Version},",
    "};",
    "",
    `pub const MDN_BCD_PACKAGE_VERSION: &str = ${JSON.stringify(packageVersion)};`,
    `pub const MDN_BCD_JAVASCRIPT_ENTRY_COUNT: usize = ${entries.length};`,
    "",
    "pub fn support_rule(feature_key: &str, runtime: Runtime) -> SupportRule {",
    "  match feature_key {",
  ];

  for (const entry of entries) {
    lines.push(`    ${JSON.stringify(entry.key)} => match runtime {`);
    for (const [runtime, browser] of RUNTIME_MAPPINGS) {
      lines.push(
        `      Runtime::${runtime} => ${renderSupportRule(entry.support[browser])},`,
      );
    }
    lines.push("      _ => SupportRule::Unknown,");
    lines.push("    },");
  }

  lines.push("    _ => SupportRule::Unknown,");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  return `${lines.join("\n")}\n`;
}

function renderSupportRule(statement) {
  const versionAdded = selectVersionAdded(statement);

  if (versionAdded === true) {
    return "SupportRule::Always";
  }
  if (versionAdded === false) {
    return "SupportRule::Never";
  }
  if (typeof versionAdded !== "string") {
    return "SupportRule::Unknown";
  }

  const atOrBefore = versionAdded.match(/^≤\s*(\d+(?:\.\d+){0,3})$/u);
  if (atOrBefore) {
    return `SupportRule::AtOrBefore(${renderVersion(atOrBefore[1])})`;
  }

  if (/^\d+(?:\.\d+){0,3}$/u.test(versionAdded)) {
    return `SupportRule::Since(${renderVersion(versionAdded)})`;
  }

  return "SupportRule::Unknown";
}

function selectVersionAdded(statement) {
  if (!statement || statement === "mirror") {
    return undefined;
  }

  const statements = Array.isArray(statement) ? statement : [statement];
  const preferred =
    statements.find(
      (item) =>
        item &&
        typeof item === "object" &&
        !item.flags &&
        !item.prefix &&
        !item.alternative_name,
    ) ?? statements[0];

  return preferred?.version_added;
}

function renderVersion(version) {
  const components = version.split(".").map((component) => Number(component));
  while (components.length < 4) {
    components.push(0);
  }

  return `Version::new(${components[0]}, ${components[1]}, ${components[2]}, ${components[3]})`;
}
